Added basic calculator script in .js and site in .html
jkn1k/biblioteka-mysql pull request #4
Opened 2024-10-11 12:21 UTC by jkn1k

2024-10-14 11:26 UTC, kamilzawadzki-tomtom requested changes

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +    let liczba1 = parseFloat(document.getElementById('liczba1').value);
I would use const here

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +    let liczba2 = parseFloat(document.getElementById('liczba2').value);
I would use const here

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +    let operacja = document.getElementById('operacja').value;
I would use const here

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +    if (operacja === 'dodawanie') {
expected loop here will be switch case

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +    document.getElementById('wynik').textContent = `Wynik: ${wynik}`;
we also expect the result to be a comment so as not to divide by zero

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +    document.getElementById('wynik').textContent = `Wynik: ${wynik}`;
Using "textContent" will return the complete text content, including the hidden text. However, using "innerText" will only return the visible text content, excluding the hidden text.

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/index.html
> +        <label for="liczba1">Pierwsza liczba:</label>
u can use .placeholder,  then you have 1 line of code
https://www.w3schools.com/jsref/prop_text_placeholder.asp

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/index.html
> +        <label for="liczba2">Druga liczba:</label>
the same here

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/index.html
> +    <h2 id="wynik"></h2>
this line can be like this? please check :)
`<h2>Wynik: <span id="result"></span></h2>`

2024-10-14 11:26 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +    } else if (operacja === 'dzielenie') {
use switch case and 
when u divide you can also add a comment: 'Nie można dzielić przez zero!

2024-10-14 12:43 UTC, kamilzawadzki-tomtom requested changes

2024-10-14 12:43 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +            }
pls add default

2024-10-15 09:14 UTC, kamilzawadzki-tomtom requested changes

2024-10-15 09:14 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +document.getElementById('calculator').addEventListener('submit', function(event) {
this file is missing the following: break and line endings. before sending the code please make sure it works

2024-10-15 09:14 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +    document.getElementById('wynik').innerText = `${wynik}`;
you can just use: wynik. check if it works.

2024-10-15 09:14 UTC, kamilzawadzki-tomtom commented on kalkulator/index.html
> +<!DOCTYPE html>
please close comments as resolved or add comments because it is not known whether you have fixed it or not.

2024-10-15 09:15 UTC, kamilzawadzki-tomtom commented on kalkulator/script.js
> +document.getElementById('calculator').addEventListener('submit', function(event) {
at the moment the .js script does not work correctly for the operation: divide.

2024-10-15 12:03 UTC, jkn1k commented on kalkulator/script.js
> +    document.getElementById('wynik').innerText = `${wynik}`;
Works.

2024-10-15 13:45 UTC, kamilzawadzki-tomtom approved these changes
LGTM

2024-10-15 13:51 UTC, merged